import type { Metadata } from "next";
import { Inter, Manrope } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { ReactQueryClientProvider } from "@/provider/react-query-client-provider";
import { Toaster } from "sonner";
import { ThemeProvider } from "@/provider/theme-provider";
import AppLayout from "@/components/PublicLayout/Layout";
import { headers } from "next/headers";
import { WagmiProvider } from "wagmi";
import { config } from "@/configs/wagmi";
import { manrope } from "@/assests/fonts";
import dynamic from 'next/dynamic';
export const metadata: Metadata = {
  title: "B3 Bridge",
  description: "Generated by create next app",
};
// export const manrope = Manrope({
//   subsets: ['latin'],
//   variable: '--font-manrope',
// });
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

const WagmiProviderWrapper = dynamic(() => import('@/app/_components/WagmiWrapperProvider'), {
  ssr: false,
});
  return (
    <html lang="en" suppressHydrationWarning className={`${manrope.variable}`}>
      <head>
        <link rel="icon" type="image/png" sizes="32x32" href={"/images/logo.svg"} />
        <link rel="icon" type="image/png" sizes="16x16" href={"/images/logo.svg"} />
        {/* <link rel="preload" href="/images/banner.png" as="image" /> */}
      </head> 
      <body>

      <ReactQueryClientProvider>
          <Toaster
            theme="dark"
            richColors
            duration={3000}
            position="top-right"
            closeButton
          />  
          <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
          >
            <AppLayout>
              
              <WagmiProviderWrapper>
                
                  {children}  

</WagmiProviderWrapper>
                </AppLayout>
              
          </ThemeProvider>
      </ReactQueryClientProvider>
      </body>
    </html>
  );
}