import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { ReactQueryClientProvider } from "@/provider/react-query-client-provider";
import { Toaster } from "sonner";
import { ThemeProvider } from "@/provider/theme-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      {/* <head>
        <link rel="icon" type="image/png" sizes="32x32" href={favicon32.src} />
        <link rel="icon" type="image/png" sizes="16x16" href={favicon16.src} />
        <link rel="preload" href="/images/banner.png" as="image" />
      </head> */} 
      <body className={cn(`${inter.className}`)} >
      <ReactQueryClientProvider>
          {/* <ReactQueryDevtools initialIsOpen={false} /> */}
          <Toaster
            theme="dark"
            richColors
            duration={3000}
            position="top-right"
            closeButton
          />  
          <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
      </ReactQueryClientProvider>
      </body>
    </html>
  );
}
